"""add ticket_classification and ticket_classification_item

Revision ID: fd64c93d450b
Revises: 66cc2a2107e7
Create Date: 2026-09-17 17:18:47.080674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd64c93d450b'
down_revision: Union[str, Sequence[str], None] = '66cc2a2107e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_classifications_workspace_id'), 'ticket_classifications', ['workspace_id'], unique=False)
    op.create_table('ticket_classification_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classification_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['ticket_classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_classification_items_classification_id'), 'ticket_classification_items', ['classification_id'], unique=False)
    op.create_index(op.f('ix_ticket_classification_items_ticket_id'), 'ticket_classification_items', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_classification_items_ticket_id'), table_name='ticket_classification_items')
    op.drop_index(op.f('ix_ticket_classification_items_classification_id'), table_name='ticket_classification_items')
    op.drop_table('ticket_classification_items')
    op.drop_index(op.f('ix_ticket_classifications_workspace_id'), table_name='ticket_classifications')
    op.drop_table('ticket_classifications')
    # ### end Alembic commands ###
